language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
before_install:
  - pip install pytest-cov
  - pip install requests==2.21.0  # last version that still supports py 3.4
  - pip install coveralls
install:
  - pip install .
script:
  - PYTHONPATH=. py.test -v --cov=assertpy --cov-report term-missing tests
after_success:
  - coveralls
sudo: false
